/**
 * ExportServer.mjs
 *
 * Read-only HTTP server that exposes the research-data export surface.
 * Designed to run alongside the Empirica callbacks process in the
 * same container (started by `infra/scripts/empirica-entrypoint.sh`).
 *
 * Routing:
 *
 *   GET /
 *     Server-rendered HTML list page. Top-level: batches (with game
 *     and player counts). Each batch row links to a games page; each
 *     game row links to the three download endpoints. Filters apply
 *     globally to the list via the query string.
 *
 *   GET /batches
 *     JSON list of batches (for AJAX, machine clients).
 *
 *   GET /batches/:batchId
 *     JSON list of games in the batch.
 *
 *   GET /games/:gameId
 *     JSON metadata for a single game.
 *
 *   GET /games/:gameId/questionnaire.csv
 *     The questionnaire CSV (redact by default; ?raw=1 to skip).
 *
 *   GET /games/:gameId/transcript.md
 *     The chat transcript as Markdown (redact by default; ?raw=1).
 *
 *   GET /games/:gameId/bundle.zip
 *     Both + meta.json + llm-audit.jsonl in one ZIP.
 *
 * Auth:
 *
 *   This server assumes it is fronted by Cloudflare Access. The
 *   presence of the `Cf-Access-Jwt-Assertion` header (or
 *   `Cf-Access-Authenticated-User-Email`) is enough to log the
 *   requester in the audit trail. If the header is missing, the
 *   server still serves the request, but logs the requester as
 *   "unknown". A future commit can add an explicit Access JWT
 *   verification step.
 *
 * Redaction:
 *
 *   Every download response is generated by `ExportService` with
 *   `redact: true` by default. `?raw=1` opts out and the audit
 *   record carries `redact: false` so the choice is auditable.
 *
 * Filter and pagination:
 *
 *   The list page supports `?from=ISO`, `?to=ISO`, `?treatment=`,
 *   `?sequence=`, `?status=`, `?limit=`, `?offset=`. Limit is clamped
 *   to [1, 200]. Offset is non-negative. Unknown query parameters
 *   are ignored (so a stale bookmark does not break the page).
 */

import { createHash } from "node:crypto";
import fs from "node:fs";
import http from "node:http";
import { Readable } from "node:stream";

import { ExportService, ExportNotFoundError } from "./ExportService.mjs";
import { recordExportEvent } from "./ExportAudit.mjs";

const MAX_LIMIT = 200;
const DEFAULT_LIMIT = 25;

export function createExportServer({ service, auditFile, now = () => new Date().toISOString() } = {}) {
  if (!service) throw new Error("createExportServer: service is required");
  if (!auditFile) throw new Error("createExportServer: auditFile is required");

  return http.createServer(async (req, res) => {
    try {
      await route(req, res, { service, auditFile, now });
    } catch (error) {
      if (error instanceof ExportNotFoundError) {
        await sendJson(res, 404, { error: error.message });
        return;
      }
      // eslint-disable-next-line no-console
      console.error("[export-server] request failed", error);
      try {
        await sendJson(res, 500, { error: "internal error" });
      } catch {
        // socket already torn down
      }
    }
  });
}

async function route(req, res, ctx) {
  const url = new URL(req.url, "http://localhost");
  const path = url.pathname;
  const search = Object.fromEntries(url.searchParams);
  const requester = readRequester(req);
  const sourceIp = readSourceIp(req);
  const userAgent = req.headers["user-agent"] || "unknown";
  const redact = search.raw !== "1" && search.raw !== "true";
  const auditFields = { requester, sourceIp, userAgent };

  if (req.method !== "GET" && req.method !== "HEAD") {
    await sendJson(res, 405, { error: "method not allowed" });
    return;
  }

  if (path === "/" || path === "/index.html") {
    await handleListPage(req, res, ctx, search, auditFields, redact);
    return;
  }
  if (path === "/batches") {
    await handleBatchesJson(req, res, ctx, search, auditFields, redact);
    return;
  }
  const batchGames = path.match(/^\/batches\/([^/]+)\/games$/);
  if (batchGames) {
    await handleBatchGamesJson(req, res, ctx, batchGames[1], search, auditFields, redact);
    return;
  }
  const gameDetail = path.match(/^\/games\/([^/]+)$/);
  if (gameDetail) {
    await handleGameJson(req, res, ctx, gameDetail[1], auditFields);
    return;
  }
  const questionnaireCsv = path.match(/^\/games\/([^/]+)\/questionnaire\.csv$/);
  if (questionnaireCsv) {
    await handleQuestionnaireCsv(req, res, ctx, questionnaireCsv[1], redact, auditFields);
    return;
  }
  const transcriptMd = path.match(/^\/games\/([^/]+)\/transcript\.md$/);
  if (transcriptMd) {
    await handleTranscriptMd(req, res, ctx, transcriptMd[1], redact, auditFields);
    return;
  }
  const bundleZip = path.match(/^\/games\/([^/]+)\/bundle\.zip$/);
  if (bundleZip) {
    await handleBundleZip(req, res, ctx, bundleZip[1], redact, auditFields);
    return;
  }
  // TEMP debug: /__debug/scopes?kinds=game&ids=...&first=5
  if (path === "/__debug/scopes") {
    const filter = [];
    if (search.kinds) filter.push({ kinds: search.kinds.split(",") });
    if (search.ids) filter.push({ ids: search.ids.split(",") });
    if (search.kvs) filter.push({ kvs: JSON.parse(search.kvs) });
    const args = { first: Number(search.first) || 5 };
    if (filter.length > 0) args.filter = filter;
    try {
      const r = await ctx.service.admin.scopes(args);
      // Make robust against any shape; admin returns either {edges:[...], pageInfo}
      // or sometimes a different structure
      const edges = r?.edges || (Array.isArray(r) ? r.map((n) => ({ node: n })) : []);
      const first3 = edges.slice(0, 3).map((e) => {
        const node = e?.node || e;
        return {
          id: node?.id,
          kind: node?.kind,
          name: node?.name,
          attrCount: node?.attributes?.length || 0,
          firstAttrs: (node?.attributes || []).slice(0, 5).map((a) => ({
            key: a?.key,
            val: typeof a?.val === "string" ? a.val.slice(0, 80) : a?.val,
            hasValue: a?.value !== undefined,
            aKeys: a ? Object.keys(a) : null,
          })),
        };
      });
      await sendJson(res, 200, {
        argsSent: args,
        rawType: Array.isArray(r) ? "array" : typeof r,
        rawKeys: r ? Object.keys(r) : null,
        rawSample0: edges[0] ? Object.keys(edges[0]) : null,
        edgeCount: edges.length,
        pageInfo: r?.pageInfo || null,
        sample: first3,
      });
    } catch (e) {
      await sendJson(res, 500, { error: e.message, stack: e.stack });
    }
    return;
  }
  await sendJson(res, 404, { error: "not found" });
}

async function handleListPage(req, res, ctx, search, auditFields, redact) {
  const filter = parseListFilter(search);
  const batchLimit = clampInt(search.limit, DEFAULT_LIMIT, 1, MAX_LIMIT);
  const batches = await ctx.service.listBatches(filter);
  const trimmed = batches.slice(0, batchLimit);
  const gamesByBatch = await Promise.all(
    trimmed.map(async (b) => {
      const games = await ctx.service.listGames(b.id, { limit: MAX_LIMIT, offset: 0 });
      return { batchId: b.id, games: games.items };
    }),
  );
  const html = renderListPage({
    batches: trimmed,
    gamesByBatch,
    filter,
    limit: batchLimit,
  });
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "list-batches", format: "html", redact, filter, sizeBytes: Buffer.byteLength(html, "utf8") },
  });
  await sendHtml(res, 200, html);
}

async function handleBatchesJson(req, res, ctx, search, auditFields, redact) {
  const filter = parseListFilter(search);
  const items = await ctx.service.listBatches(filter);
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "batches.json", format: "json", redact, filter },
  });
  await sendJson(res, 200, { items, filter });
}

async function handleBatchGamesJson(req, res, ctx, batchId, search, auditFields, redact) {
  const filter = parseListFilter(search);
  filter.limit = clampInt(search.limit, DEFAULT_LIMIT, 1, MAX_LIMIT);
  filter.offset = clampInt(search.offset, 0, 0, 1_000_000);
  const result = await ctx.service.listGames(batchId, filter);
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "batch-games.json", batchId, format: "json", redact, filter },
  });
  await sendJson(res, 200, result);
}

async function handleGameJson(req, res, ctx, gameId, auditFields) {
  const bundle = await ctx.service.getGameBundle(gameId);
  const summary = {
    id: bundle.game.id,
    treatment: bundle.game.treatment,
    sequenceId: bundle.game.sequenceId,
    startedAt: bundle.game.startedAt,
    endedAt: bundle.game.endedAt,
    status: bundle.game.status,
    playerCount: bundle.players.length,
    roundCount: bundle.rounds.length,
    llmLogEntryCount: bundle.llmLog.length,
    players: bundle.players.map((p) => ({ id: p.id, name: p.name })),
  };
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "game.json", gameId, format: "json", redact: true },
  });
  await sendJson(res, 200, summary);
}

async function handleQuestionnaireCsv(req, res, ctx, gameId, redact, auditFields) {
  const { csv } = await ctx.service.renderQuestionnaireCsv(gameId, { redact });
  const sha = createHash("sha256").update(csv).digest("hex");
  const size = Buffer.byteLength(csv, "utf8");
  // Write the audit record before flushing the response so the test
  // (and any downstream consumer that reads the audit immediately
  // after a 200) sees a consistent state.
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "questionnaire.csv", gameId, format: "csv", redact, sizeBytes: size, sha256: sha },
  });
  sendCsvHeaders(res, { filename: `${gameId}.questionnaire.csv`, sha });
  if (req.method === "HEAD") {
    res.end();
  } else {
    res.end(csv, "utf8");
  }
}

async function handleTranscriptMd(req, res, ctx, gameId, redact, auditFields) {
  const { markdown } = await ctx.service.renderTranscriptMd(gameId, { redact });
  const sha = createHash("sha256").update(markdown).digest("hex");
  const size = Buffer.byteLength(markdown, "utf8");
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "transcript.md", gameId, format: "markdown", redact, sizeBytes: size, sha256: sha },
  });
  sendHeaders(res, 200, {
    "content-type": "text/markdown; charset=utf-8",
    "content-disposition": `attachment; filename="${gameId}.transcript.md"`,
    "etag": `"${sha}"`,
    "x-redact-applied": redact ? "true" : "false",
  });
  if (req.method === "HEAD") {
    res.end();
  } else {
    res.end(markdown, "utf8");
  }
}

async function handleBundleZip(req, res, ctx, gameId, redact, auditFields) {
  // We need to know size + sha256 before we can record the audit entry,
  // but the archive streams to the response as it produces bytes. Buffer
  // the entire ZIP into memory first, then atomically send the response
  // and write the audit. Real research bundles are small (<1 MB);
  // a streaming-aware audit could be added later if we need >100 MB.
  const chunks = [];
  const sink = new (await import("node:stream")).Writable({
    write(chunk, _enc, cb) {
      chunks.push(chunk);
      cb();
    },
  });
  const { bytes, sha256 } = await ctx.service.writeGameBundle(gameId, { redact, output: sink });
  await recordExportEvent({
    auditFile: ctx.auditFile,
    record: { ...auditFields, endpoint: "bundle.zip", gameId, format: "zip", redact, sizeBytes: bytes, sha256 },
  });
  res.writeHead(200, {
    "content-type": "application/zip",
    "content-disposition": `attachment; filename="${gameId}.bundle.zip"`,
    "content-length": String(bytes),
    "x-redact-applied": redact ? "true" : "false",
  });
  if (req.method === "HEAD") {
    res.end();
    return;
  }
  res.end(Buffer.concat(chunks));
}

// ── Helpers ─────────────────────────────────────────────────────────────

function parseListFilter(search) {
  const out = {};
  if (typeof search.from === "string" && search.from) out.fromISO = search.from;
  if (typeof search.to === "string" && search.to) out.toISO = search.to;
  if (typeof search.status === "string" && search.status) out.status = search.status;
  if (typeof search.treatment === "string" && search.treatment) out.treatment = search.treatment;
  if (typeof search.sequence === "string" && search.sequence) out.sequenceId = search.sequence;
  return out;
}

function clampInt(value, fallback, min, max) {
  if (value === undefined || value === null || value === "") return fallback;
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(max, Math.trunc(n)));
}

function readRequester(req) {
  // Cloudflare Access surfaces the verified user via two headers. The
  // Access-Authenticated-User-Email is the readable form; the JWT is
  // the signed form (not used here, recorded for audit completeness).
  const email = req.headers["cf-access-authenticated-user-email"];
  if (typeof email === "string" && email.length > 0) return email;
  const jwt = req.headers["cf-access-jwt-assertion"];
  if (typeof jwt === "string" && jwt.length > 0) return `cf-jwt:${jwt.slice(0, 32)}…`;
  return "unknown";
}

function readSourceIp(req) {
  const cf = req.headers["cf-connecting-ip"];
  if (typeof cf === "string" && cf.length > 0) return cf;
  const xff = req.headers["x-forwarded-for"];
  if (typeof xff === "string" && xff.length > 0) return xff.split(",")[0].trim();
  return req.socket?.remoteAddress || "unknown";
}

function sendHeaders(res, status, headers) {
  res.writeHead(status, { "cache-control": "no-store", ...headers });
}

async function sendJson(res, status, payload) {
  const body = JSON.stringify(payload, null, 2);
  sendHeaders(res, status, { "content-type": "application/json; charset=utf-8" });
  if (res.req?.method === "HEAD") {
    res.end();
  } else {
    res.end(body, "utf8");
  }
}

function sendCsvHeaders(res, { filename, sha }) {
  sendHeaders(res, 200, {
    "content-type": "text/csv; charset=utf-8",
    "content-disposition": `attachment; filename="${filename}"`,
    "etag": `"${sha}"`,
  });
}

async function sendHtml(res, status, html) {
  sendHeaders(res, status, { "content-type": "text/html; charset=utf-8" });
  res.end(html, "utf8");
}

function renderListPage({ batches, gamesByBatch, filter, limit }) {
  const gameMap = new Map(gamesByBatch.map((g) => [g.batchId, g.games]));
  const filterChips = [];
  for (const [k, v] of Object.entries(filter)) {
    if (v) filterChips.push(`<span class="chip">${escapeHtml(k)}=${escapeHtml(String(v))}</span>`);
  }
  const batchRows = batches.length === 0
    ? `<tr><td colspan="5" class="empty">No batches match the current filter.</td></tr>`
    : batches
        .map((b) => {
          const games = gameMap.get(b.id) || [];
          return `
            <tr class="batch">
              <td class="mono">${escapeHtml(b.id)}</td>
              <td>${escapeHtml(b.treatment || "?")}</td>
              <td>${escapeHtml(b.status || "?")}</td>
              <td class="num">${b.gameCount}</td>
              <td class="num">${b.playerCount}</td>
            </tr>
            <tr class="games">
              <td colspan="5">
                ${games.length === 0
                  ? `<em>No games recorded.</em>`
                  : `<table class="games">
                      <thead>
                        <tr><th>Game</th><th>Treatment</th><th>Sequence</th><th>Started</th><th>Players</th><th>Downloads</th></tr>
                      </thead>
                      <tbody>
                        ${games
                          .map(
                            (g) => `
                              <tr>
                                <td class="mono">${escapeHtml(g.id)}</td>
                                <td>${escapeHtml(g.treatment || "?")}</td>
                                <td>${escapeHtml(g.sequenceId || "?")}</td>
                                <td>${escapeHtml(g.startedAt || "?")}</td>
                                <td class="num">${g.playerCount}</td>
                                <td>
                                  <a href="/games/${encodeURIComponent(g.id)}/questionnaire.csv">questionnaire.csv</a>
                                  &nbsp;·&nbsp;
                                  <a href="/games/${encodeURIComponent(g.id)}/transcript.md">transcript.md</a>
                                  &nbsp;·&nbsp;
                                  <a href="/games/${encodeURIComponent(g.id)}/bundle.zip">bundle.zip</a>
                                </td>
                              </tr>
                            `,
                          )
                          .join("")}
                      </tbody>
                    </table>`}
              </td>
            </tr>`;
        })
        .join("");
  const filterForm = `
    <form class="filters" method="get" action="/">
      <label>from <input type="datetime-local" name="from" value="${escapeAttr(filter.fromISO || "")}"></label>
      <label>to <input type="datetime-local" name="to" value="${escapeAttr(filter.toISO || "")}"></label>
      <label>treatment
        <select name="treatment">
          <option value="">(any)</option>
          <option value="static"${filter.treatment === "static" ? " selected" : ""}>static</option>
          <option value="adaptive"${filter.treatment === "adaptive" ? " selected" : ""}>adaptive</option>
        </select>
      </label>
      <label>sequence
        <select name="sequence">
          <option value="">(any)</option>
          ${["S1", "S2", "S3", "S4"]
            .map((s) => `<option value="${s}"${filter.sequenceId === s ? " selected" : ""}>${s}</option>`)
            .join("")}
        </select>
      </label>
      <label>status
        <select name="status">
          <option value="">(any)</option>
          <option value="created"${filter.status === "created" ? " selected" : ""}>created</option>
          <option value="running"${filter.status === "running" ? " selected" : ""}>running</option>
          <option value="ended"${filter.status === "ended" ? " selected" : ""}>ended</option>
        </select>
      </label>
      <label>limit <input type="number" name="limit" min="1" max="200" value="${limit}"></label>
      <button type="submit">Apply</button>
      <a href="/" class="reset">Reset</a>
    </form>
  `;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Delibra research export</title>
  <meta name="robots" content="noindex,nofollow">
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; margin: 2rem; color: #1f2937; }
    h1 { font-size: 1.4rem; margin: 0 0 0.5rem; }
    .sub { color: #6b7280; font-size: 0.95rem; margin-bottom: 1.5rem; }
    .filters { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: end; margin-bottom: 1rem; }
    .filters label { display: flex; flex-direction: column; font-size: 0.8rem; color: #4b5563; }
    .filters input, .filters select { padding: 0.4rem 0.6rem; border: 1px solid #d1d5db; border-radius: 0.375rem; font-size: 0.9rem; }
    .filters button, .filters .reset { padding: 0.45rem 0.9rem; background: #1f2937; color: #fff; border-radius: 0.375rem; text-decoration: none; font-size: 0.9rem; }
    .filters .reset { background: #e5e7eb; color: #111827; }
    .chip { display: inline-block; padding: 0.15rem 0.5rem; background: #e0e7ff; color: #3730a3; border-radius: 999px; font-size: 0.75rem; margin-right: 0.25rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
    th, td { text-align: left; padding: 0.5rem 0.6rem; border-bottom: 1px solid #e5e7eb; font-size: 0.9rem; }
    th { background: #f9fafb; font-weight: 600; }
    .mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.78rem; color: #1f2937; }
    .num { text-align: right; }
    .batch td { background: #fff; }
    .games td { background: #f9fafb; padding: 0.75rem 1rem; }
    .games table { background: #fff; border: 1px solid #e5e7eb; border-radius: 0.375rem; }
    .empty { color: #9ca3af; font-style: italic; }
    a { color: #1d4ed8; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>Delibra research export</h1>
  <p class="sub">Choose a batch and game to download the questionnaire CSV, chat transcript, or full bundle. Downloads are PII-redacted by default; pass <code>?raw=1</code> on a download URL to opt out. Every download is recorded in the audit log.</p>
  ${filterForm}
  <div class="active">${filterChips.length ? `Active filters: ${filterChips.join(" ")}` : ""}</div>
  <table>
    <thead>
      <tr><th>Batch</th><th>Treatment</th><th>Status</th><th class="num">Games</th><th class="num">Players</th></tr>
    </thead>
    <tbody>${batchRows}</tbody>
  </table>
  <p class="sub">Showing up to ${limit} batches. Use the limit field to see more.</p>
</body>
</html>`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(value) {
  return escapeHtml(value);
}

// Default factory used by the entrypoint. Production replaces this
// with a Tajriba-backed admin; tests inject a mock.
export function createDefaultExportServer({
  url,
  srtoken,
  auditFile,
  clientName = "export-server",
  defaultRedact = true,
} = {}) {
  if (!url) throw new Error("createDefaultExportServer: url is required");
  if (!srtoken) throw new Error("createDefaultExportServer: srtoken is required");
  if (!auditFile) throw new Error("createDefaultExportServer: auditFile is required");
  return (async () => {
    const { Tajriba } = await import("@empirica/tajriba");
    const taj = await Tajriba.createAndAwait(url);
    taj.useHTTP = true;
    const sessionToken = await taj.registerService(clientName, srtoken);
    const admin = await taj.sessionAdmin(sessionToken);
    const service = new ExportService({
      admin: { scopes: async (args) => admin.scopes(args), stop: () => taj.stop() },
      auditFile,
      defaultRedact,
    });
    return createExportServer({ service, auditFile });
  })();
}
